jobs:
  test:
    runs-on: ubuntu-20.04
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug environment
        run: ls -l /opt/ros/foxy/setup.bash
      - name: Run tests
        shell: bash
        run: |
          cd /root/ros2_ws
          bash -xv ./src/ros2mypkg/test/test.bash /root

